"""
exporter.py
Handles exporting the research report as a Markdown file.
"""

from datetime import datetime


def build_markdown(question: str, report: str, sources: list[dict]) -> str:
    """Build a complete Markdown document with metadata."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    source_lines = []
    for i, src in enumerate(sources, 1):
        source_lines.append(f"{i}. [{src['title']}]({src['url']})")

    sources_md = "\n".join(source_lines)

    markdown = f"""# WARISE Research Report

**Generated:** {timestamp}
**Question:** {question}

---

{report}

---

## References

{sources_md}

---
*Generated by WARISE — Web Augmented Research Intelligence and Synthesis Engine*
"""
    return markdown


def get_filename(question: str) -> str:
    """Generate a safe filename from the question."""
    safe = "".join(c for c in question if c.isalnum() or c in " -_")
    safe = safe[:50].strip().replace(" ", "_")
    return f"WARISE_{safe}.md"
